-- =============================================================================
-- 001_materi_tajwid.sql
-- Materi Tajwid berbasis data: surah -> ayat -> materi_tajwid -> highlight_tajwid
--
-- Cara menjalankan:
--   1. Buka Supabase Dashboard > SQL Editor > New query
--   2. Tempel seluruh isi file ini
--   3. Klik Run
--
-- File ini aman dijalankan berulang kali (idempotent).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. TABEL surah
--    id diisi manual dengan nomor surah (1-114) oleh script import,
--    sehingga ayat.surah_id selalu sama dengan nomor surah.
-- -----------------------------------------------------------------------------
create table if not exists public.surah (
  id           bigint primary key,
  nama_arab    text not null,
  nama_latin   text not null,
  jumlah_ayat  integer not null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.surah is 'Daftar surah Al-Qur an. id = nomor surah (1-114).';

-- -----------------------------------------------------------------------------
-- 2. TABEL ayat
-- -----------------------------------------------------------------------------
create table if not exists public.ayat (
  id             bigint generated by default as identity primary key,
  surah_id       bigint not null references public.surah (id) on delete cascade,
  nomor_ayat     integer not null,
  teks_arab      text not null,
  terjemahan     text,
  audio_url      text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  -- Kunci alami: satu ayat unik per surah. Dipakai oleh import agar aman diulang.
  constraint ayat_surah_nomor_unik unique (surah_id, nomor_ayat),
  constraint ayat_nomor_positif check (nomor_ayat > 0)
);

comment on table public.ayat is 'Ayat lengkap beserta terjemahan Indonesia dan audio.';

-- -----------------------------------------------------------------------------
-- 3. TABEL materi_tajwid
-- -----------------------------------------------------------------------------
create table if not exists public.materi_tajwid (
  id            bigint generated by default as identity primary key,
  ayat_id       bigint not null references public.ayat (id) on delete cascade,
  judul         text not null,
  hukum_tajwid  text not null,
  sub_hukum     text not null,
  huruf_hukum   text[] not null default '{}',
  penjelasan    text not null,
  cara_membaca  text not null,
  urutan        integer not null default 1,
  is_published  boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  -- Kunci alami: satu materi per (ayat, urutan). Dipakai oleh script import
  -- sebagai target on conflict agar aman diulang.
  constraint materi_tajwid_ayat_urutan_unik unique (ayat_id, urutan),
  constraint materi_tajwid_urutan_positif check (urutan > 0)
);

comment on table public.materi_tajwid is
  'Satu baris = satu materi hukum tajwid yang menempel pada satu ayat utuh.';
comment on column public.materi_tajwid.huruf_hukum is
  'Huruf hijaiyah pemicu hukum ini. Dipakai untuk kotak huruf di halaman materi.';

-- -----------------------------------------------------------------------------
-- 4. TABEL highlight_tajwid
--    start_index dan end_index adalah indeks karakter pada ayat.teks_arab
--    (basis 0, end_index tidak termasuk). Jadi teks = teks_arab.slice(a, b).
-- -----------------------------------------------------------------------------
create table if not exists public.highlight_tajwid (
  id          bigint generated by default as identity primary key,
  materi_id   bigint not null references public.materi_tajwid (id) on delete cascade,
  teks        text not null,
  start_index integer not null,
  end_index   integer not null,
  label       text not null,
  audio_url   text,
  catatan     text,
  urutan      integer not null default 1,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  constraint highlight_tajwid_urutan_beres check (start_index >= 0 and end_index > start_index),
  constraint highlight_tajwid_kunci_unik unique (materi_id, start_index, end_index)
);

comment on table public.highlight_tajwid is
  'Potongan ayat yang di-highlight beserta nama hukum dan audio per kata.';

-- -----------------------------------------------------------------------------
-- 5. CONSTRAINT UNTUK TABEL YANG SUDAH PERNAH DIBUAT
--    Unique constraint hanya bisa ditambah lewat alter table, jadi untuk
--    instalasi lama (tabel sudah ada dari versi file sebelumnya) ditambahkan
--    di sini lewat DO block.
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.materi_tajwid'::regclass
      and conname = 'materi_tajwid_ayat_urutan_unik'
  ) then
    alter table public.materi_tajwid
      add constraint materi_tajwid_ayat_urutan_unik unique (ayat_id, urutan);
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 6. INDEX
--    Query halaman materi selalu memfilter is_published dan mengurutkan urutan.
--    Pencarian materi per ayat sudah dilayani index unique (ayat_id, urutan).
-- -----------------------------------------------------------------------------
create index if not exists materi_tajwid_published_urutan_idx
  on public.materi_tajwid (is_published, urutan);

drop index if exists public.materi_tajwid_ayat_id_idx;

create index if not exists highlight_tajwid_materi_id_idx
  on public.highlight_tajwid (materi_id, urutan);

-- -----------------------------------------------------------------------------
-- 7. updated_at otomatis
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists surah_set_updated_at on public.surah;
create trigger surah_set_updated_at
  before update on public.surah
  for each row execute function public.set_updated_at();

drop trigger if exists ayat_set_updated_at on public.ayat;
create trigger ayat_set_updated_at
  before update on public.ayat
  for each row execute function public.set_updated_at();

drop trigger if exists materi_tajwid_set_updated_at on public.materi_tajwid;
create trigger materi_tajwid_set_updated_at
  before update on public.materi_tajwid
  for each row execute function public.set_updated_at();

drop trigger if exists highlight_tajwid_set_updated_at on public.highlight_tajwid;
create trigger highlight_tajwid_set_updated_at
  before update on public.highlight_tajwid
  for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- 8. ROW LEVEL SECURITY
--    Halaman materi memakai anon key, jadi tabel harus bisa dibaca publik.
--    Menulis hanya lewat service_role (script import) atau admin di Dashboard.
-- -----------------------------------------------------------------------------
alter table public.surah            enable row level security;
alter table public.ayat             enable row level security;
alter table public.materi_tajwid    enable row level security;
alter table public.highlight_tajwid enable row level security;

drop policy if exists "baca surah publik" on public.surah;
create policy "baca surah publik" on public.surah
  for select to anon, authenticated using (true);

drop policy if exists "baca ayat publik" on public.ayat;
create policy "baca ayat publik" on public.ayat
  for select to anon, authenticated using (true);

drop policy if exists "baca materi_tajwid publik" on public.materi_tajwid;
create policy "baca materi_tajwid publik" on public.materi_tajwid
  for select to anon, authenticated using (is_published = true);

drop policy if exists "baca highlight_tajwid publik" on public.highlight_tajwid;
create policy "baca highlight_tajwid publik" on public.highlight_tajwid
  for select to anon, authenticated
  using (exists (
    select 1
    from public.materi_tajwid m
    where m.id = highlight_tajwid.materi_id
      and m.is_published = true
  ));

grant usage on schema public to anon, authenticated;
grant select on public.surah            to anon, authenticated;
grant select on public.ayat             to anon, authenticated;
grant select on public.materi_tajwid    to anon, authenticated;
grant select on public.highlight_tajwid to anon, authenticated;

-- -----------------------------------------------------------------------------
-- 9. STORAGE BUCKET audio-tajwid
--    Bucket publik supaya <audio> bisa memutar tanpa signed URL.
-- -----------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('audio-tajwid', 'audio-tajwid', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "baca audio tajwid publik" on storage.objects;
create policy "baca audio tajwid publik" on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'audio-tajwid');

drop policy if exists "unggah audio tajwid" on storage.objects;
create policy "unggah audio tajwid" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'audio-tajwid');
